Code Review Request.
KelynPNjeri/Restaurant-Page pull request #1
Opened 2021-01-12 15:40 UTC by KelynPNjeri

Herein is the code for the Restaurant Page application. It makes use of Vanilla JS and Webpack to transpile the Javascript and manage and optimize the assets within the project.

2021-01-12 16:54 UTC, Dandush03 requested changes
# Status: :red_circle: Require Changes :red_circle: 
### Great work so far :muscle: checkout my comments below
- [x] It features a tabbed menu. When a tab is clicked the content is replaced ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- [x] The contents of each tab are stored in a `module`. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- [ ] Each `module` exports a function that creates a `<div>` element, adds the appropriate content and styles to that element and then appends it to the DOM. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))

# Happy Coding :computer: :nerd_face:

2021-01-12 16:54 UTC, Dandush03 commented on package.json
> +  },
### Scripts:
### Let's add the proper inviroment for each script
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2021-01-12 16:54 UTC, Dandush03 commented on webpack.config.js
> +
### webpack
- [ ]  usage of `import` and `export` instead of `require` or `module.exports`

2021-01-18 20:26 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello @KelynPNjeri   👋 
You are doing a great job with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received from the previous TSE. 🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] When the user clicks on a tab that they are already, it adds the information to the page another time. See my screenshots below for clarification 👇🏾 
Screenshot from first time user clicks 'contact us' 👇🏾 
<img width="522" alt="Screen Shot 2021-01-18 at 3 19 26 PM" src="https://user-images.githubusercontent.com/48804258/104959588-8ff88380-59a0-11eb-839e-3086d334f318.png">
Screenshot when user clicks contact us again 👇🏾 
<img width="488" alt="Screen Shot 2021-01-18 at 3 19 49 PM" src="https://user-images.githubusercontent.com/48804258/104959620-9be44580-59a0-11eb-81c0-7cdb0126654b.png">
* This happens on both the contact us tab and the main menu tab. 


****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-02-08 18:22 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @KelynPNjeri :hand: 
Great job implementing the requested changes.
However, the linter checks didn't pass in your last commit. 

- [x] We need to make sure both eslint and stylint checks pass

Happy coding :computer: 
**Sergio Torres**

2021-02-08 18:44 UTC, Torres-ssf approved these changes
### PR Approved :+1: 
Hello again.
Your PR is approved.
You may merge the PR now.

Happy coding :computer: 
**Sergio Torres**

2021-02-08 18:45 UTC, merged